version: "3"
services:

    redmine:
      image: redmine
      restart: always
      ports:
        - 8080:3000
      volumes:
        - /srv/docker/redmine:/usr/src/redmine/files
      environment:
        REDMINE_DB_MYSQL: db
        REDMINE_DB_PASSWORD: example
      networks:
        - apinet
    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: example
        MYSQL_DATABASE: redmine
      networks:
        - apinet
     
networks:
    apinet:
