version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: users
    volumes:
      - docker-data:/data/db
      - ./db-init/:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
        - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
  docker-data:
    name: users-mogoDB-data