version: "3"
services:

    wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
      - /srv/docker/wordpress/wp-content:/var/www/html/wp-content
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     networks:
       - apinet
    db:
     image: mysql:5.7
     volumes:
       - /srv/docker/mysql:/var/lib/mysql
     ports:
       - "3306:3306"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     networks:
       - apinet

networks:
    apinet: