version: "3"

services:
  shadowsocks:
    container_name: shadowsocks
    image: oddrationale/docker-shadowsocks
    ports:
      - "443:8989"
    restart: always
    command: -s 0.0.0.0 -p 8989 -k wuyunan+ -m aes-256-cfb
    networks:
      - ssservice
networks:
  ssservice:
